### ISSUE TITLE
Removing Stale Endpoints from CCM

### ISSUE THREAD

**Issue by adilio** [chocolatey/ChocoCCM#48]
Customers have asked for a programmatic way to deprecate/remove endpoints that have not checked in for a certain period of time.

Some of the logic in `Get-CCMComputer` could accomplish a part of this, being able to evaluate the property of when the endpoint last checked into CCM.

If there was a way to define a max check-in time interval after which to remove the endpoint from CCM, that's what this `Remove-CCMComputer` or `Remove-CCMStaleComputer` would act on. You could set a `-MaxLastCheckinDays` value as a parameter.

**Comment by steviecoaster** [comment]
This could be useful, but requires an additional permission, that isn't enabled by default even on the `ccmadmin` account.

So this feature would require the following:

- [ ] A new cmdlet for managing permissions: `Set-CCMPermission`
- [ ] A check for the required permission on the user session
- [ ] Creation of `Remove-CCMComputer` cmdlet
- [ ] Addtional parameter on `Get-CCMComputer` called `-MaxLastCheckInDays`

**Comment by Foxavoavo** [comment]
Hello, will be great to have Remove-CCMComputer

or even a script that does this computer housekeep once per month. 

I have an array to compare computers with AD but then I need to go an remove computers from Chocolatey Central Management manually.

**Comment by ryanrichter94** [comment]
Closing this issue as Stale Computer Deletion was added into the settings of CCM itself as a feature the [0.10.0 release of CCM](https://docs.chocolatey.org/en-us/central-management/release-notes#august-30-2022). Please reference the [CCM Usage Docs](https://docs.chocolatey.org/en-us/central-management/usage/website/administration/settings/stale-computer-deletion) for a full breakdown of the feature and how to enable and configure it.
