### ISSUE TITLE
Add-CCMGroupMember fails with 400 error

### ISSUE THREAD

**Issue by adilio** [chocolatey/ChocoCCM#50]
### What You Are Seeing?
When attempting to use the example in docs:

`Add-CCMGroupMember -Group 'Newly Imaged' -Computer Lab1,Lab2,Lab3`

We are seeing:
![image](https://user-images.githubusercontent.com/21287462/122486441-f1dc0a00-cf8d-11eb-8eff-264db1c98f25.png)

### What is Expected?
We should be able to add members to a group.

### Prognosis
Add-CCMGroupMember should have the `-Name` field be required, but then the parameter sets should handle whether `-Computer` or `-Group` is required.

As of right now,  _both_ `-Name` and `-Group` are required. This may be the result of multiple parameter sets. As well, the `[400] Bad Request` error is output every time.

We have tried this with both the `-master` and `-develop` branches.

**Comment by ryanrichter94** [comment]
Had a support ticket today where this issue came up. [ZenDesk Ticket](https://chocolatey.zendesk.com/agent/tickets/11156).

**Comment by ryanrichter94** [comment]
Have another [ZenDesk ticket](https://chocolatey.zendesk.com/agent/tickets/11206) where this came up.

**Comment by ryanrichter94** [comment]
Have another support ticket regarding this issue [ZenDesk Ticket](https://chocolatey.zendesk.com/agent/tickets/12879).

**Comment by jma89** [comment]
I had this same issue and fixed it on my local copy of the module.

Single line fix: Line 228: Change from @() to ''

This corrects the underlying issue of bad JSON being generated and passed to the server.

I can put a pull request together with the fix shortly.

**Comment by jma89** [comment]
Actually, it looks like Gep13's PRs (they've already been merged into the develop branch as of Mid-September) addressed this through some refactoring in that function.

As of today (2023-02-23) it's the latest commit on the branch. Just needs to get pushed out as an update to the gallery.
