### ISSUE TITLE
Using Add-CCMGroup or Add-CCMGroupMember results in an HTTP (400) Bad request error

### ISSUE THREAD

**Issue by dominiquestabile** [chocolatey/ChocoCCM#59]
### What You Are Seeing?
Add-CCMGroup and Add-CCMGroup Function returns: The remote server returned an error: (400) Bad Request

### What is Expected?
The Group should be created without errors.
### How Did You Get This To Happen? (Steps to Reproduce)
Just run the function.
### Output Log
![image](https://user-images.githubusercontent.com/43202821/148172358-7abf32ff-fe53-423e-9554-12a3d28144b3.png)

The following section of both function has a bug:
`$body = @{` 
`Name        = $Name`
`Id          = ($groups | Where-Object { $_.name -eq "$Name" } | Select-Object  -ExpandProperty Id)`
`Description = ($groups | Where-Object { $_.name -eq "$Name" } | Select-Object  -ExpandProperty Description)`
`	Groups      = if (-not $processedGroups) { @() } else { @(,$processedGroups) }`
`	Computers   = if (-not $processedComputers) { @() } else { @(,$processedComputers) }`
` `
`} | ConvertTo-Json -Depth 3`

The groups and computers section of the generated JSON is not an array as it should.
To fix it should be replaced with the following (or equivalent):

`$body = @{` 
`Name        = $Name`
`Id          = ($groups | Where-Object { $_.name -eq "$Name" } | Select-Object  -ExpandProperty Id)`
`Description = ($groups | Where-Object { $_.name -eq "$Name" } | Select-Object  -ExpandProperty Description)`
 `	Groups      = if (-not $processedGroups) { @(,@()) } else { @(,@($processedGroups)) }`
 `	Computers   = if (-not $processedComputers) { @(,@()) } else { @(,@($processedComputers)) }`
` `
`} | ConvertTo-Json -Depth 3`

**Comment by Tabiskabis** [comment]
Gee, quality pay software here. Junior collegue spent several hours trying to work around these (and other) issues.
I swear i even saw some release notes saying this exact problem had been fixed, when in fact it's not.

**Comment by pauby** [comment]
@Tabiskabis I've amended your comment. Please note our [Code Of Conduct](https://github.com/chocolatey/.github/blob/6f97a2556a46dbe45ea895af3b219cb0931458a3/CODE_OF_CONDUCT.md).

**Comment by darksidemilk** [comment]
I just setup CCM and was excited to use this module and particularly this function so I could easily create an AD OU membership sync. I am also having this issue.
If I use the api/swagger section in my local website and attempt the api call with a json of just the group name, it does work fine. I noted in the verbose output that same issue @dominiquestabile describes with the malformed json. 
I would additionally say that it should check if the $computer, $group, and $description fields are null and if so not put them in the json body so empty groups can be created.
